### ISSUE TITLE
The Print version of the Pan Docs' TOC links to subpages instead of anchoring headers on the same page

### ISSUE THREAD

**Issue by GauChoob** [gbdev/pandocs#302] opened 2021-06-04 05:11 UTC
On the page https://gbdev.io/pandocs/print.html, the table of contents is not useful because cleaning on an entry will instead navigate to the subpage containing just the topic. The expected behaviour is an anchor link to the header of the section within the print version of the document.

**Comment by ISSOtm** [comment] 2021-07-01 14:41
This is actually two problems: one, links within the document link to the individual pages. Two, the sidebar links to the individual pages.

The problem common to both is being able to link to a specific "page" within the single-page version: there is not necessarily a `<h1>` at the top of each page, so it may not be possible to link to it. I need to check whether that does occur for any of the pages currently in Pan Docs.

**Comment by ISSOtm** [comment] 2021-07-20 07:14
Duplicate of #297

**Closed by ISSOtm** 2021-07-20 07:14 UTC
