### ISSUE TITLE
Consistent text width

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#100] opened 2020-12-27 01:30 UTC
Should we keep/enforce the 80 columns wrap?

**Comment by adembudak** [comment] 2021-01-05 17:02
120 is my new normal on coding and documents.

**Comment by ISSOtm** [comment] 2021-02-10 10:30
I use 100 soft, 120 hard.

That said, for prose(-ish), like `mandoc`, I prefer to put one sentence per line, not enforcing line wraps. Partly because `mandoc` needs a newline after sentence-ending periods, and partly because line wrapping is OK for prose, imo.

**Comment by ISSOtm** [comment] 2021-07-27 09:46
Duplicate of #333

**Closed by ISSOtm** 2021-07-27 09:46 UTC
Labels: awaiting feedback, consistency - style
